### ISSUE TITLE
Online tests failed for all new Swift tasks

### ISSUE THREAD

**Issue by 2Grey** [exercism/swift-test-runner#21]
I done tasks and all tests for tasks passed locally, but it failed for online test check.

Note: Locally i unskip all test before run tests;

Task list:
[Freelancer Rates](https://exercism.org/tracks/swift/exercises/freelancer-rates)
[Vexing Vehicle Purchase](https://exercism.org/tracks/swift/exercises/vehicle-purchase)
[Cal's Custom Sign Shop](https://exercism.org/tracks/swift/exercises/custom-signs)
[Double-Null0111: Closures Are Forever](https://exercism.org/tracks/swift/exercises/bomb-defuser)
[Secret Agent Double-Null0111](https://exercism.org/tracks/swift/exercises/secret-agent)

**Comment by ErikSchierboom** [comment]
@2Grey The Swift track currently does not support running online tests. There is a bug that makes it appear like it does: https://github.com/exercism/exercism/issues/5653

The main problem is that the Swift test runner doesn't even compile within its Dockerfile setup. See https://github.com/exercism/swift-test-runner/issues/12 Personally, I don't know Swift. Would you perhaps be interested in seeing if you can fix the above issue? If so, that would be fantastic as we'd be able to run the Swift test runner for all Swift exercises.

**Comment by 2Grey** [comment]
@ErikSchierboom, LGTM i think this issue can be closed.

**Comment by ErikSchierboom** [comment]
Yay! Thanks for testing.
