### ISSUE TITLE
remove TestRunner from bin

### ISSUE THREAD

**Issue by wneumann** [exercism/swift-test-runner#4]
TestRunner is currently in ./bin as a binary file, which is less than ideal. Need to find a good way to pull it out of the repo. It might be easiest to write a script to build the executable locally and copy it to ./bin.

**Comment by angelikatyborska** [comment]
`TestRunner` was already removed from `./bin` in https://github.com/exercism/swift-test-runner/pull/22 but no script to build the binary was added, and there are no instructions in the README about how to do that.

**Comment by luilver** [comment]
It is going to be added in #29.

**Comment by ErikSchierboom** [comment]
Closed by #29
